### ISSUE TITLE
invalid request

### ISSUE THREAD

**Issue by Dalkson** [maxsupermanhd/go-mc-ms-auth#3]
MS refresh attempt answered not HTTP200! Instead got 400 Bad Request and following json: map[string]interface {}{"correlation_id":"778abe04-1f41-4f49-9fc4-60fcf8ae8108", "error":"invalid_request", "error_description":"The provided request must include a 'refresh_token' input parameter."}

**Comment by maxsupermanhd** [comment]
Any steps to reproduce the issue?

**Comment by Dalkson** [comment]
I basically just copied and pasted the readme, then used my token

**Comment by maxsupermanhd** [comment]
You are likely passing wrong/broken structure to the `CheckRefreshMS` function (https://github.com/maxsupermanhd/go-mc-ms-auth/blob/master/auth.go#LL41C41-L41C41)
If token provided in the structure is expired, it will attempt to refresh it using refresh token, it is taken directly from the same structure.
